FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /App

COPY ./GameTableService ./GameTableService
COPY ./Shared/JwtConfiguration ./Shared/JwtConfiguration
COPY ./GamingTableHelper.sln .

RUN dotnet restore GameTableService/GameTableService.csproj
RUN dotnet publish GameTableService/GameTableService.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /App

LABEL project="gamingtablehelper"

COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "GameTableService.dll"]