FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /App

COPY ./ApiGateway ./ApiGateway
COPY ./Shared/JwtConfiguration ./Shared/JwtConfiguration
COPY ./GamingTableHelper.sln .

RUN dotnet restore ApiGateway/ApiGateway.csproj
RUN dotnet publish ApiGateway/ApiGateway.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "ApiGateway.dll"]