apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-gametable-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-gametable
  template:
    metadata:
      labels:
        app: mssql-gametable
    spec:
      containers:
        - name: mssql-gametable
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "Password!1" #This password should be stored in a safe place when in a real-world scenario
          volumeMounts:
            - mountPath: var/opt/mssql/data
              name: mssql-gametable-db
      volumes:
      - name: mssql-gametable-db
        persistentVolumeClaim:
          claimName: mssql-gametable-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-gametable-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mssql-gametable
  ports:
  - name: mssql-gametable
    protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-gametable-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mssql-gametable
  ports:
  - protocol: TCP
    port: 1535
    targetPort: 1433