apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-auth
  template:
    metadata:
      labels:
        app: mssql-auth
    spec:
      containers:
        - name: mssql-auth
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "Password!1" #This password should be stored in a safe place when in a real-world scenario
          volumeMounts:
            - mountPath: var/opt/mssql/data
              name: mssql-auth-db
          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
      volumes:
      - name: mssql-auth-db
        persistentVolumeClaim:
          claimName: mssql-auth-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-auth-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mssql-auth
  ports:
  - name: mssql-auth
    protocol: TCP
    port: 1433
    targetPort: 1433