apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for SQL Server..."
              until nc -z mssql-notification-clusterip-srv 1433; do
                echo "Waiting for database..."
                sleep 2
              done
              echo "Waiting for Auth Service..."
              until nc -z auth-clusterip-srv 8080; do
                echo "Waiting for auth service..."
                sleep 2
              done
              echo "All dependencies are available."
      containers:
        - name: notification
          image: gamingtablehelper-notification
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: notification
  ports:
  - name: notification
    protocol: TCP
    port: 8080
    targetPort: 8080