FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /App

COPY ./AuthService ./AuthService
COPY ./Shared/JwtConfiguration ./Shared/JwtConfiguration
COPY ./GamingTableHelper.sln .

RUN dotnet restore AuthService/AuthService.csproj
RUN dotnet publish AuthService/AuthService.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /App

LABEL project="gamingtablehelper"

COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "AuthService.dll"]